### ISSUE TITLE
Telephone Directory

### ISSUE THREAD

**Issue by krvikas1011** [krvikas1011/LLD-Examples#1]
## Acceptance Criteria
- [x] Create a microservice to work as a telephone directory
- [x] Users should be able to create contacts and store phone numbers (1 number per person)
- [x] Users should be able to update phone numbers
- [x] There can be multiple people with the same name
- [ ] Code should be unit tested
- [x] Microservice should be containerized

Constraint: We are trying to design an in-memory system without using any database, etc.

**Comment by shubhaangi04** [comment]
Completed and closed.
